import Context from "@/components/Context";
import SearchProvider from "@/context/SearchContext";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "./services/AuthProvider";
import Navbar from "./share/Navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Stock-Z",
  description: "Generated by create next app",
  icons: {
    icon: "/public/assets/logo-new.png",
  },
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-[#F2F9FF]`}>
        <AuthProvider>
          <SearchProvider>
            <Context>
              <Navbar />
              <div className="h-screen">{children}</div>
            </Context>
          </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
