import Navbar from "@/app/share/Navbar";
import Context from "@/components/Context";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "./services/AuthProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Stock-Z",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-[#F2F9FF]`}>
        <AuthProvider>
          <Context>
              <Navbar />
            <div className="h-screen">{children}</div>
          </Context>
        </AuthProvider>
      </body>
    </html>
  );
}
